# Configuration file for the STM32 for VSCode extension
# Arrays can be inputted in two ways. One is: [entry_1, entry_2, ..., entry_final]
# or by adding an indented list below the variable name e.g.:
# VARIABLE:
# - entry_1
# - entry_2

# The project name
target: m4_fw_CM4
# Can be C or C++
language: C

optimization: Og

# MCU settings
targetMCU: stm32mp15x
cpu: cortex-m4 # type of cpu e.g. cortex-m4
fpu: fpv4-sp-d16 # Defines how floating points are defined. Can be left empty.
floatAbi: hard
ldscript: CM4/STM32MP151AACX_RAM.ld # linker script

# Compiler definitions. The -D prefix for the compiler will be automatically added.
cDefinitions: 
  - DEBUG
  - CORE_CM4
  - NO_ATOMIC_64_SUPPORT
  - METAL_INTERNAL
  - METAL_MAX_DEVICE_REGIONS=2
  - VIRTIO_SLAVE_ONLY
  - USE_HAL_DRIVER
  - STM32MP151Axx

cxxDefinitions: 
  - DEBUG
  - CORE_CM4
  - NO_ATOMIC_64_SUPPORT
  - METAL_INTERNAL
  - METAL_MAX_DEVICE_REGIONS=2
  - VIRTIO_SLAVE_ONLY
  - USE_HAL_DRIVER
  - STM32MP151Axx

asDefinitions: []

# Compiler definition files. you can add a single files or an array of files for different definitions.
# The file is expected to have a definition each new line.
# This allows to include for example a .definition file which can be ignored in git and can contain
# This can be convenient for passing along secrets at compile time, or generating a file for per device setup.
cDefinitionsFile:
cxxDefinitionsFile:
asDefinitionsFile:

# Compiler flags
cFlags: []
cxxFlags: 
  - -feliminate-unused-debug-types

assemblyFlags: []
linkerFlags: 
  - -specs=nosys.specs


# libraries to be included. The -l prefix to the library will be automatically added.
libraries: 
  - c
  - m
  - nosys

# Library directories. Folders can be added here that contain custom libraries.
libraryDirectories: []

# Files or folders that will be excluded from compilation.
# Glob patterns (https://www.wikiwand.com/en/Glob_(programming)) can be used.
# Do mind that double stars are reserved in yaml
# these should be escaped with a: \ or the name should be in double quotes e.g. "**.test.**"
excludes: 
  - "**/Examples/**"
  - "**/examples/**"
  - "**/Example/**"
  - "**/example/**"
  - "**_template.*"


# Include directories (directories containing .h or .hpp files)
# If a CubeMX makefile is present it will automatically include the include directories from that makefile.
includeDirectories: 
  - CM4/Core/Inc
  - CM4/OPENAMP
  - Middlewares/Third_Party/OpenAMP/open-amp/lib/include
  - Middlewares/Third_Party/OpenAMP/libmetal/lib/include
  - Drivers/STM32MP1xx_HAL_Driver/Inc
  - Drivers/STM32MP1xx_HAL_Driver/Inc/Legacy
  - Drivers/CMSIS/Device/ST/STM32MP1xx/Include
  - Middlewares/Third_Party/OpenAMP/virtual_driver
  - Drivers/CMSIS/Include
  - CM4/Inc/**
  - CM4/Core/Inc/**
  - CM4/Core/Lib/**
  - CM4/Src/**
  - CM4/Core/Src/**
  - CM4/Core/Lib/**


# Files that should be included in the compilation.
# If a CubeMX makefile is present it will automatically include the  c and cpp/cxx files from that makefile.
# Glob patterns (https://www.wikiwand.com/en/Glob_(programming)) can be used.
# Do mind that double stars are reserved in yaml
# these should be escaped with a: \ or the name should be in double quotes e.g. "HARDWARE_DRIVER*.c"
sourceFiles:  
  - CM4/Core/Startup/startup_stm32mp151aacx.s
  - Common/System/system_stm32mp1xx.c
  - CM4/OPENAMP/**
  - Drivers/STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal.c
  - Drivers/STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_cortex.c
  - Drivers/STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_dma.c
  - Drivers/STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_dma_ex.c
  - Drivers/STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_exti.c
  - Drivers/STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_gpio.c
  - Drivers/STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_hsem.c
  - Drivers/STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_ipcc.c
  - Drivers/STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_mdma.c
  - Drivers/STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_pwr.c
  - Drivers/STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_pwr_ex.c
  - Drivers/STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_rcc.c
  - Drivers/STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_rcc_ex.c
  - Drivers/STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_spi.c
  - Drivers/STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_spi_ex.c
  - Drivers/STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_tim.c
  - Drivers/STM32MP1xx_HAL_Driver/Src/stm32mp1xx_hal_tim_ex.c
  - Middlewares/Third_Party/OpenAMP/open-amp/lib/proxy/CMakeLists.txt
  - Middlewares/Third_Party/OpenAMP/libmetal/lib/system/generic/condition.c
  - Middlewares/Third_Party/OpenAMP/libmetal/lib/device.c
  - Middlewares/Third_Party/OpenAMP/libmetal/lib/system/generic/generic_device.c
  - Middlewares/Third_Party/OpenAMP/libmetal/lib/system/generic/generic_init.c
  - Middlewares/Third_Party/OpenAMP/libmetal/lib/system/generic/generic_io.c
  - Middlewares/Third_Party/OpenAMP/libmetal/lib/system/generic/generic_shmem.c
  - Middlewares/Third_Party/OpenAMP/libmetal/lib/init.c
  - Middlewares/Third_Party/OpenAMP/libmetal/lib/io.c
  - Middlewares/Third_Party/OpenAMP/libmetal/lib/log.c
  - Middlewares/Third_Party/OpenAMP/open-amp/lib/remoteproc/remoteproc_virtio.c
  - Middlewares/Third_Party/OpenAMP/open-amp/lib/rpmsg/rpmsg.c
  - Middlewares/Third_Party/OpenAMP/open-amp/lib/rpmsg/rpmsg_virtio.c
  - Middlewares/Third_Party/OpenAMP/libmetal/lib/shmem.c
  - Middlewares/Third_Party/OpenAMP/libmetal/lib/system/generic/template/sys.c
  - Middlewares/Third_Party/OpenAMP/libmetal/lib/system/generic/time.c
  - Middlewares/Third_Party/OpenAMP/virtual_driver/virt_uart.c
  - Middlewares/Third_Party/OpenAMP/open-amp/lib/virtio/virtio.c
  - Middlewares/Third_Party/OpenAMP/open-amp/lib/virtio/virtqueue.c
  - CM4/Src/**
  - CM4/Core/Src/**
  - CM4/Core/Lib/**


# When no makefile is present it will show a warning pop-up.
# However when compilation without the CubeMX Makefile is desired, this can be turned of.
suppressMakefileWarning: false

# Custom makefile rules
# Here custom makefile rules can be added to the STM32Make.make file
# an example of how this can be used is commented out below.
customMakefileRules:
# - command: sayhello
#   rule: echo "hello"
#   dependsOn: $(BUILD_DIR)/$(TARGET).elf # can be left out    

# Additional flags which will be used when invoking the make command
makeFlags:
# - -O  # use this option when the output of make is mixed up only works for make version 4.0 and upwards
# - --silent # use this option to silence the output of the build
    